// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2, build R23)
// Generated source version: 1.1.2

package org.freebxml.omar.common.jaxrpc.notificationListener.client;

import javax.xml.rpc.*;

public interface NotificationListenerSOAPService extends javax.xml.rpc.Service {
    public org.freebxml.omar.common.jaxrpc.notificationListener.client.NotificationListenerPortType getNotificationListenerPort() throws ServiceException;
}
