// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.freebxml.omar.common.jaxrpc.cms.cataloging.client;

public interface ContentCatalogingServicePortType extends java.rmi.Remote {
    public javax.xml.soap.SOAPElement catalogContent(javax.xml.soap.SOAPElement partCatalogContentRequest) throws 
         java.rmi.RemoteException;
}
