// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.freebxml.omar.common.jaxrpc.cms.cataloging.client;

import javax.xml.rpc.*;

public interface ContentCatalogingServiceSOAPService extends javax.xml.rpc.Service {
    public org.freebxml.omar.common.jaxrpc.cms.cataloging.client.ContentCatalogingServicePortType getContentCatalogingServicePort() throws ServiceException;
}
