// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.freebxml.omar.common.jaxrpc.registry.client;

public interface QueryManagerPortType extends java.rmi.Remote {
    public javax.xml.soap.SOAPElement submitAdhocQuery(javax.xml.soap.SOAPElement partAdhocQueryRequest) throws 
         java.rmi.RemoteException;
}
