// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.freebxml.omar.common.jaxrpc.cms.validation.client;

import javax.xml.rpc.*;

public interface ContentValidationServiceSOAPService extends javax.xml.rpc.Service {
    public org.freebxml.omar.common.jaxrpc.cms.validation.client.ContentValidationServicePortType getContentValidationServicePort() throws ServiceException;
}
