// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2, build R23)
// Generated source version: 1.1.2

package org.freebxml.omar.common.jaxrpc.notificationListener.server;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.server.*;
import javax.xml.rpc.handler.HandlerInfo;
import com.sun.xml.rpc.client.HandlerChainImpl;

public class NotificationListenerPortType_Tie
    extends com.sun.xml.rpc.server.TieBase implements SerializerConstants {
    
    
    
    public NotificationListenerPortType_Tie() throws Exception {
        super(new org.freebxml.omar.common.jaxrpc.notificationListener.server.NotificationListenerSOAPService_SerializerRegistry().getRegistry());
        initialize(internalTypeMappingRegistry);
    }
    
    /*
     * This method does the actual method invocation for operation: onObjectRefsNotification
     */
    private void invoke_onObjectRefsNotification(StreamingHandlerState state) throws Exception {
        
        flushHttpResponse(state);
        javax.xml.soap.SOAPElement mySOAPElement = null;
        Object mySOAPElementObj =
            state.getRequest().getBody().getValue();
        
        if (mySOAPElementObj instanceof SOAPDeserializationState) {
            mySOAPElement = (javax.xml.soap.SOAPElement)((SOAPDeserializationState)mySOAPElementObj).getInstance();
        } else {
            mySOAPElement = (javax.xml.soap.SOAPElement)mySOAPElementObj;
        }
        
        try {
            ((org.freebxml.omar.common.jaxrpc.notificationListener.server.NotificationListenerPortType) getTarget()).onObjectRefsNotification(mySOAPElement);
            
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method does the actual method invocation for operation: onObjectsNotification
     */
    private void invoke_onObjectsNotification(StreamingHandlerState state) throws Exception {
        
        flushHttpResponse(state);
        javax.xml.soap.SOAPElement mySOAPElement = null;
        Object mySOAPElementObj =
            state.getRequest().getBody().getValue();
        
        if (mySOAPElementObj instanceof SOAPDeserializationState) {
            mySOAPElement = (javax.xml.soap.SOAPElement)((SOAPDeserializationState)mySOAPElementObj).getInstance();
        } else {
            mySOAPElement = (javax.xml.soap.SOAPElement)mySOAPElementObj;
        }
        
        try {
            ((org.freebxml.omar.common.jaxrpc.notificationListener.server.NotificationListenerPortType) getTarget()).onObjectsNotification(mySOAPElement);
            
        } catch (javax.xml.rpc.soap.SOAPFaultException e) {
            SOAPFaultInfo fault = new SOAPFaultInfo(e.getFaultCode(),
                e.getFaultString(), e.getFaultActor(), e.getDetail());
            SOAPBlockInfo faultBlock = new SOAPBlockInfo(com.sun.xml.rpc.encoding.soap.SOAPConstants.QNAME_SOAP_FAULT);
            faultBlock.setValue(fault);
            faultBlock.setSerializer(new SOAPFaultInfoSerializer(false, e.getDetail()==null));
            state.getResponse().setBody(faultBlock);
            state.getResponse().setFailure(true);
        }
    }
    
    /*
     * This method must determine the opcode of the operation that has been invoked.
     */
    protected void peekFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        if (bodyReader.getName().equals(ns1_onObjectRefsNotification_ObjectRefsNotification_QNAME)) {
            state.getRequest().setOperationCode(onObjectRefsNotification_OPCODE);
        }
        else if (bodyReader.getName().equals(ns1_onObjectsNotification_ObjectsNotification_QNAME)) {
            state.getRequest().setOperationCode(onObjectsNotification_OPCODE);
        }
        else {
            throw new SOAPProtocolViolationException("soap.operation.unrecognized", bodyReader.getName().toString());
        }
    }
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case onObjectRefsNotification_OPCODE:
                deserialize_onObjectRefsNotification(bodyReader, deserializationContext, state);
                break;
            case onObjectsNotification_OPCODE:
                deserialize_onObjectsNotification(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the onObjectRefsNotification operation.
     */
    private void deserialize_onObjectRefsNotification(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        Object mySOAPElementObj =
            ns1_ns1_ObjectRefsNotification_TYPE_QNAME_Serializer.deserialize(ns1_onObjectRefsNotification_ObjectRefsNotification_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_onObjectRefsNotification_ObjectRefsNotification_QNAME);
        bodyBlock.setValue(mySOAPElementObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the onObjectsNotification operation.
     */
    private void deserialize_onObjectsNotification(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingHandlerState state) throws Exception {
        Object mySOAPElementObj =
            ns1_ns1_ObjectsNotificationType_TYPE_QNAME_Serializer.deserialize(ns1_onObjectsNotification_ObjectsNotification_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_onObjectsNotification_ObjectsNotification_QNAME);
        bodyBlock.setValue(mySOAPElementObj);
        state.getRequest().setBody(bodyBlock);
    }
    
    
    /*
     * This method must invoke the correct method on the servant based on the opcode.
     */
    protected void processingHook(StreamingHandlerState state) throws Exception {
        switch (state.getRequest().getOperationCode()) {
            case onObjectRefsNotification_OPCODE:
                invoke_onObjectRefsNotification(state);
                break;
            case onObjectsNotification_OPCODE:
                invoke_onObjectsNotification(state);
                break;
            default:
                throw new SOAPProtocolViolationException("soap.operation.unrecognized", Integer.toString(state.getRequest().getOperationCode()));
        }
    }
    
    protected String getDefaultEnvelopeEncodingStyle() {
        return null;
    }
    
    public String getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    
    /*
     * This method must determine the opcode of the operation given the QName of the first body element.
     */
    public int getOpcodeForFirstBodyElementName(QName name) {
        if (name == null) {
            return InternalSOAPMessage.NO_OPERATION;
        }
        if (name.equals(ns1_onObjectRefsNotification_ObjectRefsNotification_QNAME)) {
            return onObjectRefsNotification_OPCODE;
        }
        if (name.equals(ns1_onObjectsNotification_ObjectsNotification_QNAME)) {
            return onObjectsNotification_OPCODE;
        }
        return super.getOpcodeForFirstBodyElementName(name);
    }
    
    
    private Method internalGetMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
        
        Method theMethod = null;
        
        switch(opcode) {
            case onObjectRefsNotification_OPCODE:
                {
                    Class[] carray = { javax.xml.soap.SOAPElement.class };
                    theMethod = (org.freebxml.omar.common.jaxrpc.notificationListener.server.NotificationListenerPortType.class).getMethod("onObjectRefsNotification", carray);
                }
                break;
            
            case onObjectsNotification_OPCODE:
                {
                    Class[] carray = { javax.xml.soap.SOAPElement.class };
                    theMethod = (org.freebxml.omar.common.jaxrpc.notificationListener.server.NotificationListenerPortType.class).getMethod("onObjectsNotification", carray);
                }
                break;
            
            default:
        }
        return theMethod;
    }
    
    private Method[] methodMap = new Method[2];
    
    /*
     * This method returns the Method Obj for a specified opcode.
     */
    public Method getMethodForOpcode(int opcode) throws ClassNotFoundException, NoSuchMethodException {
         
        if (opcode <= InternalSOAPMessage.NO_OPERATION ) {
            return null;
        }
         
        if (opcode >= 2 ) {
            return null;
        }
         
        if (methodMap[opcode] == null)  {
            methodMap[opcode] = internalGetMethodForOpcode(opcode);
        }
         
        return methodMap[opcode];
    }
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected String[] getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public QName[] getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    
    protected boolean preHandlingHook(StreamingHandlerState state) throws Exception {
        boolean bool = false;
        bool = super.preHandlingHook(state);
        return bool;
    }
    
    
    protected void postResponseWritingHook(StreamingHandlerState state) throws Exception {
        super.postResponseWritingHook(state);
    }
    
    private void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_ns1_ObjectRefsNotification_TYPE_QNAME_Serializer = (CombinedSerializer)registry.getSerializer("", javax.xml.soap.SOAPElement.class, ns1_ObjectRefsNotification_TYPE_QNAME);
        ns1_ns1_ObjectsNotificationType_TYPE_QNAME_Serializer = (CombinedSerializer)registry.getSerializer("", javax.xml.soap.SOAPElement.class, ns1_ObjectsNotificationType_TYPE_QNAME);
    }
    
    private static final QName portName = new QName("urn:your:urn:goes:here", "NotificationListenerPort");
    private static final int onObjectRefsNotification_OPCODE = 0;
    private static final int onObjectsNotification_OPCODE = 1;
    private static final QName ns1_onObjectRefsNotification_ObjectRefsNotification_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", "ObjectRefsNotification");
    private static final QName ns1_ObjectRefsNotification_TYPE_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", "ObjectRefsNotification");
    private CombinedSerializer ns1_ns1_ObjectRefsNotification_TYPE_QNAME_Serializer;
    private static final QName ns1_onObjectsNotification_ObjectsNotification_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", "ObjectsNotification");
    private static final QName ns1_ObjectsNotificationType_TYPE_QNAME = new QName("urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0", "ObjectsNotificationType");
    private CombinedSerializer ns1_ns1_ObjectsNotificationType_TYPE_QNAME_Serializer;
    private static final String[] myNamespace_declarations =
                                        new String[] {
                                            "ns0", "urn:oasis:names:tc:ebxml-regrep:xsd:query:3.0"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
